name: Test code with jest

on: 
push:
   paths: 
    - ./leetcode

jobs:
  test:
    runs-os: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
