name: Testing with jest

on:
  push:
    paths:
      - ./leetcode/**

jobs:
  build:
    runs-os: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install deps
        run: npm install

      - name: Test code
        run: npm test
